In [69]:
from dataclasses import field
import numpy
import pandas as pd
from mimesis import Generic, Field, Fieldset, Schema
from mimesis.locales import Locale
from mimesis.plugins.pytest import mimesis
from mimesis.random import random
from datetime import datetime, timedelta
import pytest

In [70]:
# Генерим зарегестрированных пользователей
user_fs = Fieldset(locale=Locale.EN, i=20)
user_df = pd.DataFrame.from_dict({
    "id": list(range(1, 21)),
    "name": user_fs("name"),
    "login": user_fs("username"),
    "password": user_fs("password")
})
user_df

    id        name             login  password
0    1    Catherin      sending_2053  5kHins1(
1    2      Babara   structural_1879  @SmL23P~
2    3       Ciera       sleeve_1982  cbo7T*Iu
3    4      Rosana      finance_1970  yY*F"m_#
4    5       Royce  playstation_1913  $vN/{w0b
5    6      Nancee        stack_1894  A|y"s@$#
6    7      Lindsy  acquisition_2005  v7fVq4~.
7    8         Rob       george_2089  y#wb"|.e
8    9     Ernesto        image_2017  ,JQQ^1,A
9   10       Teddy          him_2093  \e:Z+(=u
10  11  Bernardina         acre_1949  rJB[">~X
11  12        Shon          sat_1828  ((uL$e}@
12  13     Jestine      website_1841  ^.+bNbjX
13  14     Emerald        shift_2038  B"(liYZ[
14  15      Mickey         used_1984  \:uu~UO>
15  16       Bryce  instruments_2085  |"U(0=pQ
16  17    Larraine        kitty_2011  `us-}&r*
17  18   Domonique     petition_1812  S~Mh[FHF
18  19         Peg     illinois_1995  hYQWbw@*
19  20      Andres     launched_2021  gk&5e]W&

In [71]:
# Генерим темы
theme_fs = Fieldset(locale=Locale.EN, i=10)
theme_df = pd.DataFrame.from_dict({
    "id": list(range(1, 11)),
    "name": theme_fs("word"),
    "text": theme_fs("text"),
    "creation_date": theme_fs("datetime"),
    "creator_id": random.randints(10, 1, 21)
})
theme_df

,id,name,text,creation_date,creator_id
0,1,lib,Its main implementation is the Glasgow Haskell Compiler. Ports are used to communicate with the external world. It is also a garbage-collected runtime system. Type classes first appeared in the Haskell programming language. Atoms are used within a program to denote distinguished values.,2025-07-03 23:02:51.741227,7
1,2,wrong,"Erlang is a general-purpose, concurrent, functional programming language. Atoms can contain any character if they are enclosed within single quotes and an escape convention exists which allows any character to be used within an atom. Haskell features a type system with type inference and lazy evaluation. Its main implementation is the Glasgow Haskell Compiler. I don't even care.",2025-07-09 04:42:16.446705,4
2,3,perform,"They are written as strings of consecutive alphanumeric characters, the first character being lowercase. It is also a garbage-collected runtime system. Type classes first appeared in the Haskell programming language. Atoms can contain any character if they are enclosed within single quotes and an escape convention exists which allows any character to be used within an atom. Do you have any idea why this is not working?",2025-01-02 13:52:01.077317,5
3,4,cam,"Type classes first appeared in the Haskell programming language. Messages can be sent to and received from ports, but these messages must obey the so-called ""port protocol."" In 1989 the building was heavily damaged by fire, but it has since been restored. The syntax {D1,D2,...,Dn} denotes a tuple whose arguments are D1, D2, ... Dn. Where are my pants?",2025-01-06 09:30:25.742035,13
4,5,developments,"I don't even care. Haskell is a standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing. Type classes first appeared in the Haskell programming language. Tuples are containers for a fixed number of Erlang data types. Ports are used to communicate with the external world.",2025-06-13 05:37:10.169332,5
5,6,district,"The sequential subset of Erlang supports eager evaluation, single assignment, and dynamic typing. Type classes first appeared in the Haskell programming language. She spent her earliest years reading classic literature, and writing poetry. Atoms are used within a program to denote distinguished values. Ports are created with the built-in function open_port.",2025-02-24 19:37:18.656775,11
6,7,rings,"Make me a sandwich. Initially composing light-hearted and irreverent works, he also wrote serious, sombre and religious pieces beginning in the 1930s. Ports are used to communicate with the external world. They are written as strings of consecutive alphanumeric characters, the first character being lowercase. The syntax {D1,D2,...,Dn} denotes a tuple whose arguments are D1, D2, ... Dn.",2025-02-23 15:53:49.759095,17
7,8,pl,Ports are created with the built-in function open_port. Tuples are containers for a fixed number of Erlang data types. Erlang is known for its designs that are well suited for systems. Make me a sandwich. Do you come here often?,2025-05-18 09:56:51.516284,5
8,9,meeting,"The Galactic Empire is nearing completion of the Death Star, a space station with the power to destroy entire planets. Atoms can contain any character if they are enclosed within single quotes and an escape convention exists which allows any character to be used within an atom. They are written as strings of consecutive alphanumeric characters, the first character being lowercase. The sequential subset of Erlang supports eager evaluation, single assignment, and dynamic typing. The syntax {D1,D2,...,Dn} denotes a tuple whose arguments are D1, D2, ... Dn.",2025-03-04 01:23:05.907323,1
9,10,portal,"Its main implementation is the Glasgow Haskell Compiler. Do you have any idea why this is not working? The Galactic Empire is nearing completion of the Death Star, a space station with the power to destroy entire planets. The syntax {D1,D2,...,Dn} denotes a tuple whose arguments are D1, D2, ... Dn. Haskell features a type system with type inference and lazy evaluation.",2025-11-27 19:44:34.685579,4

In [74]:
# Генерим сообщения
#Сгенерируем количество анонимных и неанонимных сообщений
random_anonym_messages_choices = random.choices([True, False], k=50)
#Сгенерируем пользователя к каждому неанонимному сообщению
creator_id_with_anonym_messages = []
for boolean in random_anonym_messages_choices:
    if not boolean:
        creator_id_with_anonym_messages.append(random.randint(1, 21))
    else:
        creator_id_with_anonym_messages.append(None)

message_fs = Fieldset(locale=Locale.EN, i=50)
message_df = pd.DataFrame.from_dict({
    "id": list(range(1, 51)),
    "text": message_fs("text"),
    "creation_date": message_fs("datetime"),
    "theme_id": random.randints(50, 1, 9),
    "creator_id": creator_id_with_anonym_messages,
    "anonymous": random_anonym_messages_choices
})
message_df

,id,text,creation_date,theme_id,creator_id,anonymous
0,1,"Any element of a tuple can be accessed in constant time. They are written as strings of consecutive alphanumeric characters, the first character being lowercase. Any element of a tuple can be accessed in constant time. Initially composing light-hearted and irreverent works, he also wrote serious, sombre and religious pieces beginning in the 1930s. Do you have any idea why this is not working?",2025-07-17 15:33:32.886575,2,19.0,False
1,2,"Haskell is a standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing. Type classes first appeared in the Haskell programming language. Do you come here often? Do you come here often? Tuples are containers for a fixed number of Erlang data types.",2025-09-21 03:19:41.334059,5,9.0,False
2,3,"Its main implementation is the Glasgow Haskell Compiler. Erlang is a general-purpose, concurrent, functional programming language. Atoms can contain any character if they are enclosed within single quotes and an escape convention exists which allows any character to be used within an atom. Initially composing light-hearted and irreverent works, he also wrote serious, sombre and religious pieces beginning in the 1930s. The Galactic Empire is nearing completion of the Death Star, a space station with the power to destroy entire planets.",2025-08-10 04:49:51.948241,5,NaN,True
3,4,"Erlang is known for its designs that are well suited for systems. Ports are created with the built-in function open_port. Type classes first appeared in the Haskell programming language. Make me a sandwich. Messages can be sent to and received from ports, but these messages must obey the so-called ""port protocol.""",2025-02-21 01:26:09.289636,1,5.0,False
4,5,"It is also a garbage-collected runtime system. She spent her earliest years reading classic literature, and writing poetry. Haskell is a standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing. It is also a garbage-collected runtime system. Do you come here often?",2025-02-26 15:56:48.376082,3,NaN,True
5,6,"Make me a sandwich. Haskell features a type system with type inference and lazy evaluation. Atoms can contain any character if they are enclosed within single quotes and an escape convention exists which allows any character to be used within an atom. She spent her earliest years reading classic literature, and writing poetry. Haskell features a type system with type inference and lazy evaluation.",2025-09-17 11:07:07.274088,3,NaN,True
6,7,"She spent her earliest years reading classic literature, and writing poetry. It is also a garbage-collected runtime system. Make me a sandwich. Any element of a tuple can be accessed in constant time. Erlang is a general-purpose, concurrent, functional programming language.",2025-06-26 02:13:31.586569,5,10.0,False
7,8,Its main implementation is the Glasgow Haskell Compiler. Tuples are containers for a fixed number of Erlang data types. I don't even care. Ports are created with the built-in function open_port. I don't even care.,2025-10-20 01:05:26.294249,6,NaN,True
8,9,"Ports are used to communicate with the external world. Erlang is a general-purpose, concurrent, functional programming language. The arguments can be primitive data types or compound data types. The sequential subset of Erlang supports eager evaluation, single assignment, and dynamic typing. Erlang is known for its designs that are well suited for systems.",2025-07-29 09:22:08.156115,3,19.0,False
9,10,"Atoms can contain any character if they are enclosed within single quotes and an escape convention exists which allows any character to be used within an atom. Erlang is a general-purpose, concurrent, functional programming language. Atoms are used within a program to denote distinguished values. Do you have any idea why this is not working? Tuples are containers for a fixed number of Erlang data types.",2025-05-07 16:47:56.395711,6,13.0,False
10,11,"Tuples are containers for a fixed number of Erlang data types. The syntax {D1,D2,...,Dn} denotes a tuple whose arguments are D1, D2, ... Dn. The syntax {D1,D2,...,Dn} denotes a tuple whose arguments are D1, D2, ... Dn. Any element of a tuple can be accessed in constant time. Haskell features a type system with type inference and lazy evaluation.",2025-02-21 08:11:05.610319,1,13.0,False
11,12,"In 1989 the building was heavily damaged by fire, but it has since been restored. The sequential subset of Erlang supports eager evaluation, single assignment, and dynamic typing. Haskell features a type system with type inference and lazy evaluation. Erlang is a general-purpose, concurrent, functional programming language. The Galactic Empire is nearing completion of the Death Star, a space station with the power to destroy entire planets.",2025-10-06 14:13:04.246566,2,NaN,True
12,13,"Type classes first appeared in the Haskell programming language. Its main implementation is the Glasgow Haskell Compiler. They are written as strings of consecutive alphanumeric characters, the first character being lowercase. Make me a sandwich. Atoms are used within a program to denote distinguished values.",2025-11-04 15:36:59.371060,8,1.0,False
13,14,"Erlang is known for its designs that are well suited for systems. Messages can be sent to and received from ports, but these messages must obey the so-called ""port protocol."" Tuples are containers for a fixed number of Erlang data types. Ports are used to communicate with the external world. Erlang is known for its designs that are well suited for systems.",2025-08-01 21:26:25.038744,8,NaN,True
14,15,"Messages can be sent to and received from ports, but these messages must obey the so-called ""port protocol."" Tuples are containers for a fixed number of Erlang data types. Ports are created with the built-in function open_port. Initially composing light-hearted and irreverent works, he also wrote serious, sombre and religious pieces beginning in the 1930s. Its main implementation is the Glasgow Haskell Compiler.",2025-01-05 19:23:29.869743,7,NaN,True
15,16,"Atoms are used within a program to denote distinguished values. Type classes first appeared in the Haskell programming language. In 1989 the building was heavily damaged by fire, but it has since been restored. Ports are used to communicate with the external world. Make me a sandwich.",2025-02-26 22:16:04.177064,6,NaN,True
16,17,"Haskell is a standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing. In 1989 the building was heavily damaged by fire, but it has since been restored. She spent her earliest years reading classic literature, and writing poetry. Ports are created with the built-in function open_port. Erlang is a general-purpose, concurrent, functional programming language.",2025-03-16 05:54:57.533069,3,NaN,True
17,18,"Any element of a tuple can be accessed in constant time. Ports are used to communicate with the external world. Erlang is known for its designs that are well suited for systems. The Galactic Empire is nearing completion of the Death Star, a space station with the power to destroy entire planets. Where are my pants?",2025-05-23 06:31:10.224917,5,6.0,False
18,19,"Initially composing light-hearted and irreverent works, he also wrote serious, sombre and religious pieces beginning in the 1930s. The Galactic Empire is nearing completion of the Death Star, a space station with the power to destroy entire planets. Ports are created with the built-in function open_port. She spent her earliest years reading classic literature, and writing poetry. Erlang is a general-purpose, concurrent, functional programming language.",2025-10-08 10:43:30.062876,4,1.0,False
19,20,"Type classes first appeared in the Haskell programming language. Erlang is a general-purpose, concurrent, functional programming language. Make me a sandwich. Initially composing light-hearted and irreverent works, he also wrote serious, sombre and religious pieces beginning in the 1930s. Atoms can contain any character if they are enclosed within single quotes and an escape convention exists which allows any character to be used within an atom.",2025-02-04 06:33:27.399744,5,21.0,False
20,21,Ports are created with the built-in function open_port. He looked inquisitively at his keyboard and wrote another sentence. Do you have any idea why this is not working? Do you have any idea why this is not working? Where are my pants?,2025-08-29 00:22:47.603431,7,18.0,False
21,22,"The sequential subset of Erlang supports eager evaluation, single assignment, and dynamic typing. Its main implementation is the Glasgow Haskell Compiler. Atoms are used within a program to denote distinguished values. Atoms are used within a program to denote distinguished values. Do you have any idea why this is not working?",2025-07-28 09:32:12.381750,7,15.0,False
22,23,"I don't even care. The Galactic Empire is nearing completion of the Death Star, a space station with the power to destroy entire planets. They are written as strings of consecutive alphanumeric characters, the first character being lowercase. The sequential subset of Erlang supports eager evaluation, single assignment, and dynamic typing. The Galactic Empire is nearing completion of the Death Star, a space station with the power to destroy entire planets.",2025-12-19 10:55:49.936908,7,21.0,False
23,24,"Haskell is a standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing. The arguments can be primitive data types or compound data types. She spent her earliest years reading classic literature, and writing poetry. Do you come here often? Its main implementation is the Glasgow Haskell Compiler.",2025-02-14 10:31:02.845817,2,11.0,False
24,25,"Any element of a tuple can be accessed in constant time. Erlang is a general-purpose, concurrent, functional programming language. Initially composing light-hearted and irreverent works, he also wrote serious, sombre and religious pieces beginning in the 1930s. The sequential subset of Erlang supports eager evaluation, single assignment, and dynamic typing. Make me a sandwich.",2025-11-23 19:00:13.933694,8,21.0,False
25,26,"She spent her earliest years reading classic literature, and writing poetry. He looked inquisitively at his keyboard and wrote another sentence. Tuples are containers for a fixed number of Erlang data types. The syntax {D1,D2,...,Dn} denotes a tuple whose arguments are D1, D2, ... Dn. Its main implementation is the Glasgow Haskell Compiler.",2025-01-05 22:17:00.982295,1,NaN,True
26,27,"The arguments can be primitive data types or compound data types. She spent her earliest years reading classic literature, and writing poetry. The arguments can be primitive data types or compound data types. Ports are created with the built-in function open_port. Do you come here often?",2025-06-27 10:29:44.583971,3,NaN,True
27,28,"In 1989 the building was heavily damaged by fire, but it has since been restored. Do you have any idea why this is not working? Any element of a tuple can be accessed in constant time. Erlang is known for its designs that are well suited for systems. She spent her earliest years reading classic literature, and writing poetry.",2025-08-29 00:50:59.535254,4,12.0,False
28,29,"The syntax {D1,D2,...,Dn} denotes a tuple whose arguments are D1, D2, ... Dn. Haskell is a standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing. Messages can be sent to and received from ports, but these messages must obey the so-called ""port protocol."" The syntax {D1,D2,...,Dn} denotes a tuple whose arguments are D1, D2, ... Dn. Type classes first appeared in the Haskell programming language.",2025-01-25 10:56:28.304233,4,1.0,False
29,30,"Type classes first appeared in the Haskell programming language. Ports are used to communicate with the external world. Any element of a tuple can be accessed in constant time. Where are my pants? The sequential subset of Erlang supports eager evaluation, single assignment, and dynamic typing.",2025-10-23 11:50:02.073552,1,NaN,True
30,31,"Haskell is a standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing. They are written as strings of consecutive alphanumeric characters, the first character being lowercase. Erlang is known for its designs that are well suited for systems. The syntax {D1,D2,...,Dn} denotes a tuple whose arguments are D1, D2, ... Dn. He looked inquisitively at his keyboard and wrote another sentence.",2025-11-09 21:04:32.753359,3,10.0,False
31,32,"It is also a garbage-collected runtime system. Erlang is a general-purpose, concurrent, functional programming language. The sequential subset of Erlang supports eager evaluation, single assignment, and dynamic typing. Any element of a tuple can be accessed in constant time. I don't even care.",2025-09-07 19:14:57.941058,8,NaN,True
32,33,"Do you have any idea why this is not working? The Galactic Empire is nearing completion of the Death Star, a space station with the power to destroy entire planets. Tuples are containers for a fixed number of Erlang data types. Initially composing light-hearted and irreverent works, he also wrote serious, sombre and religious pieces beginning in the 1930s. The Galactic Empire is nearing completion of the Death Star, a space station with the power to destroy entire planets.",2025-04-12 02:03:46.259768,2,13.0,False
33,34,"It is also a garbage-collected runtime system. Erlang is known for its designs that are well suited for systems. Do you have any idea why this is not working? Messages can be sent to and received from ports, but these messages must obey the so-called ""port protocol."" He looked inquisitively at his keyboard and wrote another sentence.",2025-11-25 00:27:13.752755,4,1.0,False
34,35,"Do you come here often? They are written as strings of consecutive alphanumeric characters, the first character being lowercase. Atoms can contain any character if they are enclosed within single quotes and an escape convention exists which allows any character to be used within an atom. Do you have any idea why this is not working? Atoms are used within a program to denote distinguished values.",2025-01-04 09:29:13.094854,5,NaN,True
35,36,"I don't even care. Where are my pants? The syntax {D1,D2,...,Dn} denotes a tuple whose arguments are D1, D2, ... Dn. Haskell features a type system with type inference and lazy evaluation. Tuples are containers for a fixed number of Erlang data types.",2025-07-28 00:09:39.830664,2,NaN,True
36,37,"Ports are created with the built-in function open_port. The sequential subset of Erlang supports eager evaluation, single assignment, and dynamic typing. Ports are used to communicate with the external world. The syntax {D1,D2,...,Dn} denotes a tuple whose arguments are D1, D2, ... Dn. Ports are created with the built-in function open_port.",2025-02-05 00:07:20.759078,3,8.0,False
37,38,"Do you come here often? Initially composing light-hearted and irreverent works, he also wrote serious, sombre and religious pieces beginning in the 1930s. I don't even care. Ports are created with the built-in function open_port. Tuples are containers for a fixed number of Erlang data types.",2025-08-06 08:45:20.342555,6,NaN,True
38,39,"Atoms can contain any character if they are enclosed within single quotes and an escape convention exists which allows any character to be used within an atom. Any element of a tuple can be accessed in constant time. In 1989 the building was heavily damaged by fire, but it has since been restored. The arguments can be primitive data types or compound data types. Erlang is a general-purpose, concurrent, functional programming language.",2025-10-30 00:25:45.646014,8,NaN,True
39,40,"Atoms can contain any character if they are enclosed within single quotes and an escape convention exists which allows any character to be used within an atom. The syntax {D1,D2,...,Dn} denotes a tuple whose arguments are D1, D2, ... Dn. The sequential subset of Erlang supports eager evaluation, single assignment, and dynamic typing. Atoms are used within a program to denote distinguished values. Where are my pants?",2025-07-09 00:19:36.894690,2,NaN,True
40,41,"Where are my pants? Ports are used to communicate with the external world. I don't even care. She spent her earliest years reading classic literature, and writing poetry. Messages can be sent to and received from ports, but these messages must obey the so-called ""port protocol.""",2025-12-19 16:12:40.474550,2,6.0,False
41,42,"Atoms can contain any character if they are enclosed within single quotes and an escape convention exists which allows any character to be used within an atom. Messages can be sent to and received from ports, but these messages must obey the so-called ""port protocol."" Ports are used to communicate with the external world. Erlang is known for its designs that are well suited for systems. It is also a garbage-collected runtime system.",2025-02-01 23:12:02.742728,1,NaN,True
42,43,"Ports are used to communicate with the external world. Its main implementation is the Glasgow Haskell Compiler. Ports are created with the built-in function open_port. Ports are used to communicate with the external world. The sequential subset of Erlang supports eager evaluation, single assignment, and dynamic typing.",2025-11-08 09:16:58.258122,3,19.0,False
43,44,"Haskell is a standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing. Haskell is a standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing. Ports are created with the built-in function open_port. Tuples are containers for a fixed number of Erlang data types. The Galactic Empire is nearing completion of the Death Star, a space station with the power to destroy entire planets.",2025-08-03 13:07:23.383105,3,13.0,False
44,45,"Atoms are used within a program to denote distinguished values. Atoms are used within a program to denote distinguished values. In 1989 the building was heavily damaged by fire, but it has since been restored. He looked inquisitively at his keyboard and wrote another sentence. The arguments can be primitive data types or compound data types.",2025-07-05 17:34:23.010090,3,NaN,True
45,46,"They are written as strings of consecutive alphanumeric characters, the first character being lowercase. Do you come here often? It is also a garbage-collected runtime system. Erlang is known for its designs that are well suited for systems. Initially composing light-hearted and irreverent works, he also wrote serious, sombre and religious pieces beginning in the 1930s.",2025-12-31 02:51:39.609663,4,NaN,True
46,47,"Where are my pants? Where are my pants? Atoms are used within a program to denote distinguished values. Haskell is a standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing. Make me a sandwich.",2025-12-08 04:32:02.403230,8,4.0,False
47,48,"The Galactic Empire is nearing completion of the Death Star, a space station with the power to destroy entire planets. Haskell is a standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing. Erlang is known for its designs that are well suited for systems. Atoms can contain any character if they are enclosed within single quotes and an escape convention exists which allows any character to be used within an atom. It is also a garbage-collected runtime system.",2025-05-11 11:59:05.842341,1,16.0,False

Скриптом сгенерировать датасет содержащий для одного дня как минимум по 5 действий каждого типа. Для действия создания темы должно быть как минимум 2 случая возврата ошибки по причине отсутствия логина. Для действия написание сообщения должно быть примерно равное распределение залогиненых и незалогиненых пользователя. Скрипт для генерации должен сам выбирать число действий каждого типа используя рандомайзер но учитывая минимальные пороги.
Датасет должен содержать данные за месяц.

In [ ]:
# Создадим таблицу с действиями
action_df = pd.DataFrame.from_dict({
    "id": list(range(1, 8)),
    "description": ['first_visit', 'registration', 'login', 'logout',
    'create_theme', 'view_theme', 'delete_theme', 'create_message']})

In [79]:
# Генерим логи
date_start = datetime(2025, 2, 1)
log_id_counter = 1
logs = []
for day in range(28):
    date = date_start + timedelta(days = day)
    for action_num in range(1, 8):
        action_amount = random.randint(5, 10)
        
        #генерация ошибок создания темы
        if action_num == 5:
            for i in range(2):
                logs.append({
                    "id": log_id_counter,
                    "user_id": random.randint(11, 21),
                    "actions_id": 5,
                    "time": date + timedelta(minutes = random.randint(0, 1440)), 
                    "response": "Ошибка создания темы по причине отсутствия логина"
                })
                log_id_counter += 1
                
                
        #генерация любых действий
        for i in range(action_amount):
            logs.append({
                "id": log_id_counter,
                "user_id": random.randint(1, 21),
                "actions_id": action_num,
                "time": date + timedelta(minutes = random.randint(0, 1440)),
                "response": "Успешно!"
            })
            log_id_counter += 1
        
logs_df = pd.DataFrame(logs)
logs_df

        id  user_id  actions_id                time  response
0        1        5           1 2025-02-01 15:56:00  Успешно!
1        2        1           1 2025-02-01 12:49:00  Успешно!
2        3       12           1 2025-02-01 06:53:00  Успешно!
3        4        2           1 2025-02-01 10:26:00  Успешно!
4        5        1           1 2025-02-01 23:35:00  Успешно!
...    ...      ...         ...                 ...       ...
1514  1515       10           7 2025-02-28 19:55:00  Успешно!
1515  1516        8           7 2025-02-28 03:22:00  Успешно!
1516  1517        1           7 2025-02-28 20:16:00  Успешно!
1517  1518       21           7 2025-02-28 23:13:00  Успешно!
1518  1519        8           7 2025-02-28 18:11:00  Успешно!

[1519 rows x 5 columns]

In [81]:
#создаём файлы с данными
user_df.to_csv(header=True, index=False, path_or_buf='data_files/user_data.csv', encoding='utf-8')
theme_df.to_csv(header=True, index=False, path_or_buf='data_files/theme_data.csv', encoding='utf-8')
message_df.to_csv(header=True, index=False, path_or_buf='data_files/messages_data.csv', encoding='utf-8')
logs_df.to_csv(header=True, index=False, path_or_buf='data_files/logs_data.csv', encoding='utf-8')